services:
  - type: web
    name: slot-manager
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python generate_availability.py
    startCommand: gunicorn slot_booking_webapp:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: service_account.json
      - key: LOGIN_USERNAME
        value: admin
      - key: LOGIN_PASSWORD
        value: geheim
