services:
  - type: web
    name: slot-booking-webapp
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      # Erstelle static Ordner falls nicht vorhanden
      mkdir -p static
      # Initiale availability.json generieren (mit Timeout)
      timeout 120s python generate_availability.py || echo "Initial generation skipped"
    startCommand: gunicorn slot_booking_webapp:app --workers 2 --threads 2 --timeout 120
    envVars:
      # Automatisch generierter Secret Key
      - key: SECRET_KEY
        generateValue: true
      
      # Python Version
      - key: PYTHON_VERSION
        value: "3.11"
      
      # Google Calendar ID
      - key: CENTRAL_CALENDAR_ID
        value: zentralkalenderzfa@gmail.com
      
      # Diese müssen in Render Secrets gesetzt werden:
      # - GOOGLE_CREDS_BASE64 (base64 encoded service account JSON)
      # - USERLIST (user:pass,user2:pass2 format)
    
    # Health Check
    healthCheckPath: /login
    
    # Automatisches Scaling (für 9€ Plan)
    scaling:
      minInstances: 1
      maxInstances: 1

