services:
  - type: web
    name: slot-booking-webapp
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python generate_availability.py
    startCommand: gunicorn slot_booking_webapp:app

